name: Deploy Docusaurus

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Initialize Docusaurus if missing
      run: |
        if [ ! -f "package.json" ]; then
          npx create-docusaurus@latest api-doc classic --skip-install
          mv api-doc/* .
          rm -rf api-doc
        fi

    - name: Install dependencies
      run: npm install

    - name: Build the site
      run: npm run build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
