name: Deploy Swagger UI Docs
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build Swagger UI Docs
      run: ./make.sh
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_dir: swagger-ui
        force_orphan: true
        exclude_assets: '.github,.gitignore,README.md,make.sh,openapi.json'
